# Generated by Django 3.0.5 on 2020-04-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationpage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
