default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG: true
  SECRET_KEY: ""
  SITE_ID: 0
  CELERY_BEAT_INVITATION: -1
  CELERY_BROKER_URL: ""
  EMAIL_FROM: ""
  EMAIL_HOST: ""
  EMAIL_HOST_PASSWORD: ""
  EMAIL_HOST_USER: ""
  EMAIL_PORT: 0
  EMAIL_USE_SSL: 0
  EMAIL_USE_TLS: 0

development:
  DEBUG: true
  SITE_ID: 1
  CELERY_BEAT_INVITATION: 30

heroku:
  ALLOWED_HOSTS:
    - .ksradau.herokuapp.com
    - 127.0.0.1
    - localhost
  DEBUG: false
  CELERY_BEAT_INVITATION: 900
  SITE_ID: 1


test:
  EMAIL_FROM: "test@test.name"
  DEBUG: 1
  SECRET_KEY: "1"
  SITE_ID: 1


travis:
  EMAIL_FROM: "test@test.name"
  DEBUG: 1
  SECRET_KEY: "1"
  SITE_ID: 1